load("@rules_proto_grpc//js:repositories.bzl", rules_proto_grpc_js_repos="js_repos")

rules_proto_grpc_js_repos()

load("@build_bazel_rules_nodejs//:index.bzl", "yarn_install")

yarn_install(
    name = "npm",
    package_json = ":package.json",  # This should be changed to your local package.json which should contain the dependencies required
    yarn_lock = ":yarn.lock",
)